### PR TITLE
Fixed Css issues

### PR DESCRIPTION
**Pull request by Ojo-Triumph**

### CODE REVIEW

**Review by abiona01 — APPROVED** [review]

**Comment by abiona01** [comment]
Resolve conflict

**Review by abiona01 — COMMENTED** [review]
PULL FROM THE STAGING BRANCH, THEN MAKE YOUR PR AGAIN

**Comment by Ojo-Triumph** [comment]
That was what I did here

**Comment by abiona01** [comment]
There's still conflict. Check for the files that are conflicting in the staging branch, copy all the code their and put it in your own file

**Pull request closed without merging**
