### PR TITLE
Notification Bar Finalized

### PR DESCRIPTION
**Pull request by smit1298**
for issues #382 (create a notification view area)

### CODE REVIEW

**Comment by Asylcreek** [comment]
SO, there's a problem o. Your files are starting with .history and have weird file names. Please sort those out.

And I don't think it is possible that you changed 200 and something files, abeg check it out

If the something is giving you headache, create a new branch on your local machine, pull from the team's staging branch, make your changes, push to your github repo, then make the PR again

**Comment by KelvinAkpobome** [comment]
Squash all this commits, it's too much

**Review by abiona01 — COMMENTED** [review]
Pull from staging branch then make a new pr

**Comment by KelvinAkpobome** [comment]
Kindly squash all these commits

**Pull request closed without merging**
