### PR TITLE
missions and visions UI component

### PR DESCRIPTION
**Pull request by mowfaqqa**
Worked on the missions component in respect to issue #662 
NB: it's not yet responsive I made the PR to give the other devs something to work on at the moment as their task is dependent on this component

### CODE REVIEW

**Comment by tundealabi** [comment]
> Worked on the missions component in respect to issue #662
> NB: it's not yet responsive I made the PR to give the other devs something to work on at the moment as their task is dependent on this component

please chill on this PR😭

**Comment by mowfaqqa** [comment]
yet to be responsive

**Comment by mowfaqqa** [comment]
notify me on any errors or modifications concerning the PR. Thank you

**Comment by abiona01** [comment]
CONFLICTTTSSSSS

**Pull request merged**
