### PR TITLE
Added an endpoint to get archived goals.

### PR DESCRIPTION
**Pull request by Titophilip**

### CODE REVIEW

**Comment by Titophilip** [comment]
Somebody epp me plis. 😭😭

**Review by Adeniyii — CHANGES_REQUESTED** [review]
There are conflicts in your commit, please pull from staging and make a new PR.

**Comment by Titophilip** [comment]
I can't make any changes. I'm in church. 😭😭

**Comment by Adeniyii** [comment]
Omo, I'll see what I can do from here.

**Comment by Titophilip** [comment]
All conflicts have been resolved.

The 'eslint errors' commit just makes the code follow the conventional format; it doesn't change the working of the code.

**Pull request merged**
