### PR TITLE
This is a design for the report section

### PR DESCRIPTION
**Pull request by PeroHub**

### CODE REVIEW

**Comment by PeroHub** [comment]
Create A report component that will show the progress of the goals

#352

**Comment by KelvinAkpobome** [comment]
Please resolve conflict

**Comment by KelvinAkpobome** [comment]
You don't seem to have any issue attached to this PR, why so please?

**Comment by PeroHub** [comment]
It is saying that those with write access has the right to resolve conflict @KelvinAkpobome  and for the issue I didn't link it so the PR does not close automatically......The issue number is #352

**Comment by Asylcreek** [comment]
Please pull from the staging branch to your local branch and solve the merge conflicts there.

Then add "Closes #352" to your PR's description

**Comment by KelvinAkpobome** [comment]
Resolve conflicts please

**Pull request closed without merging**
