### PR TITLE
Project setup

### PR DESCRIPTION
**Pull request by Ibrahim-Isah**

### CODE REVIEW

**Comment by Ibrahim-Isah** [comment]
#236

**Comment by KelvinAkpobome** [comment]
Please resolve conflict

**Comment by Ibrahim-Isah** [comment]
@Asylcreek please resolve the conflict

**Comment by KelvinAkpobome** [comment]
Close #236

**Comment by Ibrahim-Isah** [comment]
The project was setup and create react app was installed using npm and it should issue #236

**Comment by Ibrahim-Isah** [comment]
Test goals.zuri.chat

**Pull request merged**
