### PR TITLE
Adjusted the responsiveness of the Goal Success Modal

### PR DESCRIPTION
**Pull request by mowfaqqa**
made it fully responsive (fingers crossed)

### CODE REVIEW

**Comment by mowfaqqa** [comment]
@tundealabi and @abiona01 please review

**Comment by abiona01** [comment]
Resolve conflicts.

**Comment by mowfaqqa** [comment]
resolved conflicts, please merge to input responsiveness of modal....

**Comment by abiona01** [comment]
@tundealabi please review

**Comment by tundealabi** [comment]
@abiona01 reviewed

**Pull request merged**
