### PR TITLE
Feat/ping

### PR DESCRIPTION
**Pull request by Ose-4g**
Created ping endpoint that returns json data when  called.

### CODE REVIEW

**Comment by Ose-4g** [comment]
closes #357

**Comment by Ose-4g** [comment]
Kindly review @Asylcreek 

close #357

**Comment by Asylcreek** [comment]
Hey man.

Please make the PR to the staging branch instead.

**Comment by Ose-4g** [comment]
Alright man. I thought I did. 

Sorry about that

**Pull request closed without merging**
