### PR TITLE
corrections on missions and vision and responsiveness

### PR DESCRIPTION
**Pull request by chuksdozie**
Alright.  this is the corrected version of the Mission and Vision tabs.
They are also responsive.

### CODE REVIEW

**Comment by abiona01** [comment]
Hi, You have conflicts to resolve. Thanks

**Comment by Ibrahim-Isah** [comment]
@abiona01 do not merge this. 
@chuksdozie can you please close this PR

**Comment by chuksdozie** [comment]
@Ibrahim-Isah why would I do that?
I stayed awake all night doing this then you wake up in the morning do your thing and you are tell me to close mine?

**Comment by Ibrahim-Isah** [comment]
@chuksdozie were you actually assigned to do the job??? It was done and merge and merging yours will cause an issue with the one the guy did.

**Comment by chuksdozie** [comment]
@Ibrahim-Isah  i was assigned to it last night, wanted to do just the edit vision but it wont make sense to do just vision and go... tunde and @abiona01 then told me to go ahead and do it


please @abiona01 respond to this, if my night has wasted let me go and rest, I dont like problem

**Comment by chuksdozie** [comment]
@abiona01 please when you are available, make a comment on this.

**Comment by Ibrahim-Isah** [comment]
@Ose-4g merge

**Pull request merged**
