### PR TITLE
added a header

### PR DESCRIPTION
**Pull request by Ibrahim-Isah**

### CODE REVIEW

**Comment by Ibrahim-Isah** [comment]
#179 


http://goals.zuri.chat

**Comment by Ibrahim-Isah** [comment]
IMG_20210831_171741_268

**Comment by KelvinAkpobome** [comment]
Please make PR to staging branch

**Comment by Draqode** [comment]
so you added the edit mission and vision header kindly check the new design and update your components to compliment the new design

**Pull request merged**
