### PR TITLE
Goal Detail Accordion updated

### PR DESCRIPTION
**Pull request by Ariiieee**
new feature content has been added to Goal detail Accordion

### CODE REVIEW

**Comment by abiona01** [comment]
You have one conflicting file. Review

**Comment by Ariiieee** [comment]
fixed conflicts

**Comment by tundealabi** [comment]
@abiona01 reviewed

**Comment by Ariiieee** [comment]
now in sync with all current updates

**Comment by abiona01** [comment]
@tundealabi review

**Pull request closed without merging**
