### PR TITLE
Validation and bugfixes

### PR DESCRIPTION
**Pull request by Ose-4g**
- Add code to validate that room id is valid
- That user cannot join same room multiple times

### CODE REVIEW

**Review by KelvinAkpobome — CHANGES_REQUESTED** [review]
Can the controllers be less concerned about the population of the sidebar components?.

**Comment by Ose-4g** [comment]
I actually didn't make any changes to the sidebar controller. 

It still works same as before.

**Comment by Ose-4g** [comment]
The controllers though useful for the sidebar. Are solely concerned with 
- creating a room for an organization
- adding user to a room
- removing user from a room.

**Review by KelvinAkpobome — COMMENTED** [review]
OK nice

**Pull request merged**
